extraction:
  cpp:
    after_prepare: 
      - python report.py 91
  cobol:
    after_prepare: 
      - python report.py 91
  csharp:
    after_prepare: 
      - python report.py 91
  java:
    after_prepare: 
      - python report.py 91
  javascript:
    after_prepare: 
      - python report.py 91
  python:
    after_prepare: 
      - python report.py 91
